### ISSUE TITLE
Monkey Madness inventory monkey dialog is attributed to last NPC spoken to

### ISSUE THREAD

**Issue by goudekid** [neilrush/npc-dialog-log#5]
See title and below images

![image](https://user-images.githubusercontent.com/13862763/119283209-23f98680-bbf1-11eb-81c7-3ae231b1e141.png)

![image](https://user-images.githubusercontent.com/13862763/119283218-29ef6780-bbf1-11eb-943f-ea275e299d83.png)

(Monkey Minders are the quest NPCs to get in and out of the cage during MM)

**Comment by neilrush** [comment]
Thank you for your issue post. Sorry I didn't see it until today. ❤
